[package]
name = "grm"
version = "0.1.0"
authors = ["Julian Didier (theredfish) <did.julian@gmail.com>"]

[dependencies]
glob = "0.2.11"

[dependencies.rusqlite]
version = "0.12.0"
features = ["bundled"]